from typing import Any, Iterable

class Cursor:
    def __enter__(self) -> "Cursor": ...
    def __exit__(self): ...
    
    description: Any = ...
    def close(self): ...
    closed: bool
    connection: "Connection"
    name: Any = ...
    scrollable: Any = ...
    withhold: Any = ...
    
    def execute(self, query: Any, vars: Any = None): ...
    def executemany(self, query: Any, vars_list: Any): ...
    callproc: Any = ...
    mogrify: Any = ...
    setinputsizes: Any = ...
    
    def fetchone(self) -> Iterable[Any]: ...
    def fetchmany(self, size: int) -> Iterable[Any]: ...
    def fetchall(self) -> Iterable[Any]: ...
    scroll: Any = ...
    arraysize: int
    itersize: int
    rowcount: int
    rownumber: int
    lastrowid: int
    query: str
    statusmessage: str
    cast: Any = ...
    tzinfo_factory: Any = ...
    nextset: Any = ...
    setoutputsize: Any = ...
    
    copy_from: Any = ...
    copy_to: Any = ...
    copy_expert: Any = ...

class Connection:
    def __enter__(self): ...
    def __exit__(self): ...
    
    def cursor(self) -> Cursor: ... 